name: Auto linter
on:
  push:
    paths: "*.py"
jobs:
  code-linter:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout/clone the code
        uses: actions/checkout@v7
      - name: install ruff linter
        run:  pip install ruff
      - name: check the file 
        run: ruff check .
    
    
  
